### PR TITLE
Provided procedure run-test-area

### PR DESCRIPTION
**Pull request by Dossar**
Parse testing to come soon

### CODE REVIEW

**Comment by YongCho** [comment]
Please note that 'racket' executable is not added to the environment 
path by default so your run-test-area procedure may have to use its full 
path. Otherwise, it may run on your pc, but not other users'.

**Comment by Dossar** [comment]
I just added a procedure which excepts the full absolute path to the racket executable, but that seems unnecessarily bulky. Regardless, both versions of the procedure are now available.

**Comment by YongCho** [comment]
I didn't mean to make it a parameter. Please use this.

(require setup/dirs)

(define RACKET-PATH
   (string-append (path->string (find-console-bin-dir))
                  (cond ((eq? (system-type) 'windows) "racket.exe")
                        ((eq? (system-type) 'unix) "/racket")
                        ((eq? (system-type) 'macosx) "/racket")
                        (else (error "Platform not supported")))))

**Comment by Dossar** [comment]
Alright, I'll try getting to that tomorrow. I have a long night ahead of me tonight.

**Comment by YongCho** [comment]
No problem. I will be working on the scheduler until the end of the 
week, so no need to hurry.

Yong J. Cho
yongjec@gmail.com

**Pull request merged**
