### PR TITLE
Implemented test area running procedures that write out test results.

### PR DESCRIPTION
**Pull request by Dossar**
Implemented test area running procedures that write out test results. I also implemented a parser for these results, and the second test area running procedure can send an email.

Going to the RACKET-PATH idea, I tried doing that and got the following error message:

'C:\Program' is not recognized as an internal or external command, operable program or batch file.

I think this also relates to how Racket says "bad path" for anything that has spaces in it. Program Files is a directory that has spaces in it. For now, I've just left the system call as racket, but changing it to RACKET-PATH is simple if there is a way to work with paths that have spaces.

### CODE REVIEW

**Comment by YongCho** [comment]
You can put " " around the path string for Windows. For Linux, You can 
use backslash in front of a space: A\ Folder\ Name. I'm not sure about 
macOS, it's probably the same as Linux.

Yong J. Cho
yongjec@gmail.com

**Comment by Dossar** [comment]
I tried that but I'm still getting errors. I could talk to you about this before Discrete Structures; maybe around 1:30 pm or so before class starts?

**Comment by YongCho** [comment]
1:30 sounds good. I'm not sure if 104 is occupied at that time. If it 
is, I'll on the second floor.

Yong J. Cho
yongjec@gmail.com

**Comment by Dossar** [comment]
I'm on the second floor right now if you want to come up. With these changes, I'll also need to change Bottle-Racket and Test-Capture since this also changes the structure of the test area files (which is a good thing! the original ones had too much extra stuff that was unnecessary).

**Pull request closed without merging**
